- gather_facts: 'no'
  hosts: KK-344
  tasks:
  - ios_config:
      lines:
      - switchport mode access
      - switchport access vlan 71
      - no cdp enable
      parents: interface Fa1/0/36
    name: Настройка порта Fa1/0/36 в VLAN 71
  - ios_config:
      lines:
      - switchport mode access
      - switchport access vlan 30
      - no cdp enable
      parents: interface Fa1/0/37
    name: Настройка порта Fa1/0/37 в VLAN 30
- gather_facts: 'no'
  hosts: KK-224
  tasks:
  - ios_config:
      lines:
      - switchport mode access
      - switchport access vlan 30
      - no cdp enable
      parents: interface Fa0/20
    name: Настройка порта Fa0/20 в VLAN 30
  - ios_config:
      lines:
      - switchport mode access
      - switchport access vlan 72
      - no cdp enable
      parents: interface Fa0/21
    name: Настройка порта Fa0/21 в VLAN 72
